/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container': '#ecedfa',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#7f2b00',
        'tertiary-container': '#973500',
        'surface-container-highest': '#e0e2ef',
        'on-secondary-container': '#64646a',
        'primary-fixed-dim': '#bac3ff',
        'on-primary-fixed': '#00105b',
        'inverse-on-surface': '#eff0fd',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ffdbce',
        'on-primary-fixed-variant': '#002fc8',
        'tertiary': '#702500',
        'background': '#faf8ff',
        'on-tertiary-fixed': '#370e00',
        'surface-bright': '#faf8ff',
        'outline-variant': '#c4c5d9',
        'on-surface-variant': '#444656',
        'secondary': '#5e5e64',
        'on-background': '#181b24',
        'primary-container': '#143ee4',
        'surface': '#faf8ff',
        'primary-fixed': '#dee0ff',
        'on-secondary-fixed': '#1a1b20',
        'primary': '#0029b3',
        'surface-tint': '#2549ed',
        'on-tertiary-container': '#ffbba1',
        'secondary-fixed-dim': '#c7c6cc',
        'tertiary-fixed-dim': '#ffb599',
        'surface-container-low': '#f2f3ff',
        'on-surface': '#181b24',
        'surface-dim': '#d8d9e6',
        'secondary-fixed': '#e3e1e8',
        'inverse-primary': '#bac3ff',
        'secondary-container': '#e3e1e8',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#46464c',
        'inverse-surface': '#2d303a',
        'surface-variant': '#e0e2ef',
        'on-primary-container': '#c0c8ff',
        'error-container': '#ffdad6',
        'outline': '#747687',
        'surface-container-high': '#e6e7f4',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '16px',
        unit: '4px',
        'margin-lg': '48px',
        'margin-sm': '16px',
        'margin-md': '32px',
        'container-padding': '24px',
        xl: '64px',
        lg: '40px',
        md: '24px',
        sm: '16px',
        xs: '8px',
        base: '4px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'hero-headline': ['Inter', 'sans-serif'],
        'card-title': ['Inter', 'sans-serif'],
        'section-headline': ['Inter', 'sans-serif'],
        'label-mono': ['IBM Plex Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-default': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'hero-headline-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'hero-headline': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'card-title': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'section-headline': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-default': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'hero-headline-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
