/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#bac3ff',
        'surface-tint': '#2549ed',
        'on-secondary-container': '#61646c',
        'on-primary-container': '#c0c8ff',
        'on-secondary-fixed-variant': '#44474e',
        'surface-variant': '#e2e1ee',
        'on-surface-variant': '#444656',
        outline: '#747687',
        'primary-fixed': '#dee0ff',
        'surface-container': '#eeecfa',
        'surface-dim': '#d8d9e5',
        'on-surface': '#1a1b24',
        'tertiary-container': '#973500',
        tertiary: '#702500',
        'secondary-fixed': '#e0e2ec',
        surface: '#faf8ff',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e2e1ee',
        secondary: '#5b5e66',
        'on-primary-fixed-variant': '#002fc8',
        'tertiary-fixed': '#ffdbce',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-low': '#f4f2ff',
        'inverse-surface': '#2f303a',
        'surface-container-high': '#e6e7f3',
        'tertiary-fixed-dim': '#ffb599',
        'outline-variant': '#c4c5d9',
        'on-tertiary-container': '#ffbba1',
        'on-background': '#1a1b24',
        'primary-fixed-dim': '#bac3ff',
        background: '#fbf8ff',
        'on-primary-fixed': '#00105b',
        'surface-bright': '#fbf8ff',
        'primary-container': '#143ee4',
        'on-secondary-fixed': '#181c22',
        primary: '#0029b3',
        'inverse-on-surface': '#f1effd',
        'on-tertiary-fixed': '#370e00',
        'secondary-fixed-dim': '#c4c6cf',
        'on-tertiary-fixed-variant': '#7f2b00',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'secondary-container': '#e0e2ec',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '64px',
        lg: '40px',
        md: '24px',
        sm: '16px',
        gutter: '16px',
        xs: '8px',
        margin: '24px',
        base: '4px',
      },
      fontFamily: {
        'body-default': ['Inter', 'sans-serif'],
        'section-headline': ['Inter', 'sans-serif'],
        'label-mono': ['IBM Plex Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'hero-headline-mobile': ['Inter', 'sans-serif'],
        'hero-headline': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'hero-headline': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'section-headline': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-default': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'hero-headline-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};


